name: CI

on:
  push:
  pull_request:

env:
  CARGO_BUILD_WARNINGS: deny

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - run: cargo clippy --all-targets --all-features

  doc:
    name: Check documentation
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - run: cargo doc --all-features

  fmt:
    name: Check format
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - name: Install nightly rustfmt
        run: |
          rustup toolchain install --profile minimal --component rustfmt nightly
          rustup default nightly
      - run: cargo fmt --all --check

  test:
    name: Test
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - run: cargo test --all-targets --all-features
